// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var controller, graph, model, paper;
    graph = new joint.dia.Graph();
    paper = new joint.dia.Paper({
      el: $('#myholder'),
      width: 1200,
      height: 600,
      model: graph,
      gridSize: 1
    });
    model = App.ShapeFactory.Model["new"]({
      name: 'test',
      attributes: [
        {
          name: "attr1",
          type: "String"
        }, {
          name: "attr2",
          type: "Number"
        }
      ],
      methods: [
        {
          name: "doStuff",
          parameters: [
            {
              name: "a",
              type: "String"
            }, {
              name: "b",
              type: "MyType"
            }
          ]
        }
      ]
    }, {
      x: 20
    });
    controller = App.ShapeFactory.Controller["new"]({
      name: 'testController',
      attributes: [
        {
          name: "attr1",
          type: "String"
        }
      ],
      methods: [
        {
          name: "doStuff",
          parameters: [
            {
              name: "a",
              type: "String"
            }, {
              name: "b",
              type: "MyType"
            }
          ]
        }
      ]
    }, {
      x: 370,
      y: 100
    });
    console.log(controller);
    graph.addCells([model, controller]);
    return graph.addCell(App.LinkFactory["new"]("Association", model, controller));
  });

}).call(this);
